status = [
  "buildkite/cardano-shell",
  "ci/hydra:Cardano:cardano-shell:required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
