# global filter; messages must have at least this severity to pass:
minSeverity: Debug

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK
  - TraceForwarderBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK
  - TraceForwarderBK

# file to forward traced objects
logOutput: "logs/log-pipe-0"

# if wanted, the GUI is listening on this port:
#hasGUI: 12871

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12781

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
    scRotation: null
  - scKind: FileSK
    scName: "launcher"
    scFormat: ScText
    scRotation: null

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - StdoutSK
    - stdout
  - - FileSK
    - "launcher"

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
