resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/b83730dccab14111d62144b048084eec7900d091/snapshot.yaml

packages:
- .
- ./cardano-launcher

extra-deps:
  - quickcheck-state-machine-0.6.0  # Used a specific dependency, new release.
  - pretty-show-1.9.5               # Used for quickcheck-state-machine.
  - time-units-1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: b83730dccab14111d62144b048084eec7900d091
    subdirs:
      - .
      - test

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054
    subdirs:
      - .

nix:
  shell-file: stack-shell.nix
