resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3c40edcf5bdba8721d3430d0aaaeea8770ce9bec/snapshot.yaml

packages:
- ./cardano-shell
- ./cardano-launcher

extra-deps:
  - katip-0.8.3.0
  - quickcheck-state-machine-0.6.0  # Used a specific dependency, new release.
  - pretty-show-1.9.5               # Used for quickcheck-state-machine.
  - time-units-1.0.0
  - silently-1.2.5.1

  - Win32-2.5.4.1@sha256:e623a1058bd8134ec14d62759f76cac52eee3576711cb2c4981f398f1ec44b85

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3c40edcf5bdba8721d3430d0aaaeea8770ce9bec
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 4956b32f039579a0e7e4fd10793f65b4c77d9044
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49
    subdirs:
      - .

nix:
  shell-file: stack-shell.nix
