resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/ad19158c7599bc5d50fe7cb0111a1488a139a381/snapshot.yaml

packages:
- ./cardano-shell
- ./cardano-launcher

extra-deps:
  - katip-0.8.3.0
  - quickcheck-state-machine-0.6.0  # Used a specific dependency, new release.
  - pretty-show-1.9.5               # Used for quickcheck-state-machine.
  - time-units-1.0.0
  - silently-1.2.5.1

  - Win32-2.5.4.1@sha256:e623a1058bd8134ec14d62759f76cac52eee3576711cb2c4981f398f1ec44b85

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ad19158c7599bc5d50fe7cb0111a1488a139a381
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: b4268cedecbbe2a35437effc17a8af10abda8ea8
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49
    subdirs:
      - .

nix:
  shell-file: stack-shell.nix
