resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/12ab51e27539c9cce042ded0c89efc0ccae6137a/snapshot.yaml

packages:
- .
- ./cardano-launcher

extra-deps:
  - quickcheck-state-machine-0.6.0  # Used a specific dependency, new release.
  - pretty-show-1.9.5               # Used for quickcheck-state-machine.
  - time-units-1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 12ab51e27539c9cce042ded0c89efc0ccae6137a
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 1ebe57df3a76a8ae4e3b5a31a9b85132f71534fc
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49
    subdirs:
      - .

nix:
  shell-file: stack-shell.nix
