resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fda38e60007a019c0c8569e8a0fc08f2102c92cc/snapshot.yaml

packages:
- .

extra-deps:
  - quickcheck-state-machine-0.6.0  # Used a specific dependency, new release.
  - pretty-show-1.9.5               # Used for quickcheck-state-machine.

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: fda38e60007a019c0c8569e8a0fc08f2102c92cc
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: e67ac43fc26e3a47ffcf1a10666f2ccd34ce8b1a
    subdirs:
      - contra-tracer
      - iohk-monitoring

  # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054
    subdirs:
      - .

  - katip-0.7.0.0@sha256:4b30d0643e18d01a3fd264d3d75921b49b2f464336a52fa46fa049107ebbfe04
  - time-units-1.0.0@sha256:27cf54091c4a0ca73d504fc11d5c31ab4041d17404fe3499945e2055697746c1
  - ekg-0.4.0.15@sha256:f52d7c00654d72d2ab988255f30adba95a52484ac310bab9c136c64732e69f4b
  - ekg-json-0.1.0.6@sha256:4ff2e9cac213a5868ae8b4a7c72a16a9a76fac14d944ae819b3d838a9725569b

  - ekg-prometheus-adapter-0.1.0.4
  - prometheus-2.1.1
  - containers-0.5.11.0
  - libsystemd-journal-1.4.4

nix:
  shell-file: stack-shell.nix
