steps:
  - label: 'check-hydra'
    command: 'ci/check-hydra.sh'
    agents:
      system: x86_64-linux
  - label: 'stack2nix'
    command: 'ci/check-regenerate-nix.sh'
    agents:
      system: x86_64-linux