steps:
  - label: 'stack coveralls coverage'
    command:
      - 'stack test --coverage'
      - 'pwd'
      - 'ls -la'
      - 'curl -L -v https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj'
      - 'ls -la'
      - 'which ./shc'
      - 'echo $COVERALLS_REPO_TOKEN'
      - './shc --repo-token=$COVERALLS_REPO_TOKEN cardano-shell cardano-shell-test'
    agents:
      system: x86_64-linux

  - label: 'nix build'
    command: 'nix-build release.nix'
    agents:
      system: x86_64-linux

  - label: 'stack rebuild'
    env:
      AWS_REGION: us-west-1
      S3_BUCKET: appveyor-ci-cache
      CACHE_S3_MAX_SIZE: 2500MB
      STACK_ROOT: "/build/cardano-shell.stack"
    command:
      - "nix-build scripts/buildkite -o stack-rebuild"
      - "./stack-rebuild --build-dir /build/cardano-shell --base-branch develop"
    agents:
      system: x86_64-linux
